kind: MLApp
metadata:
  name: speech
spec:
  package_manager: "pip3"
  default_mount_path: "/notebooks"
  packages:
    - names:
      {{- range $i, $value := .packages }}
      - "{{ $value }}"
      {{- end }}
      manager: "pip3"
  tasks:
  - name: standalone
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      images:
        gpu: "kuberlab/tensorflow:gpu-36-1.8.0-speech"
        cpu: "kuberlab/tensorflow:cpu-36-1.8.0-speech"
      command: python test.py --local --worker --num_layers 5 --hidden_size 512 --batch_size 8 --learning_rate 0.0001 --dataset_dir $VQ_DIR/train --rnn_type CudnnLSTM --input_mode vq --grad_clip 1 --save_summary_steps 10 --save_checkpoints_steps 20 --log_step_count_steps 5 --keep_checkpoint_max 2 --checkpoint_dir $TRAINING_DIR --vq_feature_size 161 --output_keep_prob 0 --rnn_state_reset_ratio 1 --lstm_direction_type bidirectional
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 8Gi
      default_volume_mapping: true
    - name: evaluator
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      images:
        gpu: "kuberlab/tensorflow:gpu-36-1.8.0-speech"
        cpu: "kuberlab/tensorflow:cpu-36-1.8.0-speech"
      command: python test.py --local --evaluator --num_layers 5 --hidden_size 512 --batch_size 8 --learning_rate 0.0001 --test_dir $VQ_DIR/dev-clean --rnn_type CudnnLSTM --input_mode vq --grad_clip 1 --save_summary_steps 10 --save_checkpoints_steps 10 --log_step_count_steps 1 --keep_checkpoint_max 2 --checkpoint_dir $TRAINING_DIR --vq_feature_size 161 --output_keep_prob 0 --rnn_state_reset_ratio 1 --lstm_direction_type bidirectional
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 8Gi
      default_volume_mapping: true
  - name: horovod
    resources:
    - name: worker
      replicas: 2
      restartPolicy: Never
      maxRestartCount: 0
      images:
        gpu: "kuberlab/tensorflow:gpu-36-1.8.0-speech"
        cpu: "kuberlab/tensorflow:cpu-36-1.8.0-speech"
      command: "board-mpi -p 2222"
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 8Gi
      port: 2222
      default_volume_mapping: true
    - name: evaluator
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      images:
        gpu: "kuberlab/tensorflow:gpu-36-1.8.0-speech"
        cpu: "kuberlab/tensorflow:cpu-36-1.8.0-speech"
      command: python test.py --local --evaluator --num_layers 5 --hidden_size 512 --batch_size 8 --learning_rate 0.0001 --test_dir $VQ_DIR/dev-clean --rnn_type CudnnLSTM --input_mode vq --grad_clip 1 --save_summary_steps 10 --save_checkpoints_steps 10 --log_step_count_steps 1 --keep_checkpoint_max 2 --checkpoint_dir $TRAINING_DIR --vq_feature_size 161 --output_keep_prob 0 --rnn_state_reset_ratio 1 --lstm_direction_type bidirectional
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 8Gi
      port: 2222
      default_volume_mapping: true
    - name: master
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      is_permanent: true
      images:
        gpu: "kuberlab/tensorflow:gpu-36-1.8.0-speech"
        cpu: "kuberlab/tensorflow:cpu-36-1.8.0-speech"
      command: mpirun --tag-output --timestamp-output -mca orte_keep_fqdn_hostnames 1 -mca pml_obl_verbose 10 -mca plm_rsh_agent board-mpi -mca plm_rsh_args "-p 2222" -H $WORKER_HOSTS python test.py --horovod --num_layers 5 --hidden_size 512 --batch_size 8 --learning_rate 0.0001 --dataset_dir $VQ_DIR/train --rnn_type CudnnLSTM --input_mode vq --grad_clip 1 --save_summary_steps 10 --save_checkpoints_steps 20 --log_step_count_steps 5 --keep_checkpoint_max 2 --checkpoint_dir $TRAINING_DIR --vq_feature_size 161 --output_keep_prob 0 --rnn_state_reset_ratio 1 --lstm_direction_type bidirectional
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 2Gi
      port: 2222
      default_volume_mapping: true
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: "kuberlab/tensorflow:gpu-36-1.8.0-speech"
      cpu: "kuberlab/tensorflow:cpu-36-1.8.0-speech"
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  - name: tensorboard
    displayName: Tensorboard
    command: "tensorboard --logdir=$TRAINING_DIR"
    images:
      gpu: "kuberlab/tensorflow:gpu-36-1.8.0-speech"
      cpu: "kuberlab/tensorflow:cpu-36-1.8.0-speech"
    ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: http
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    volumes:
    - name: training
  volumes:
  - isLibDir: false
    name: training
    clusterStorage: {{ .storage.value }}
  - gitRepo:
      repository: {{ gitRepo .src.value }}
    isLibDir: false
    name: src
    subPath: {{ gitSubPath .src.value }}
  - isLibDir: true
    name: lib
    clusterStorage: {{ .storage.value }}
  - isLibDir: false
    name: vq
    clusterStorage: kuberlab/speech
  - isLibDir: false
    mountPath: /notebooks
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
